### ISSUE TITLE
Reload

### ISSUE THREAD

**Issue by mycanaletto** [vindaalex/multizone-thermostat#5]
When reloading the thermostat (with the "C" button), I get this error that I see in Schedy. On the other hand, if I restart Home Assistant I don't have any problem.

`Unknown HVAC mode 'unknown'`

**Comment by vindaalex** [comment]
I don't use schedy but it seems it is trying to change HVAC mode to 'unknown'. This should be one of: heat, cool or off

**Comment by mycanaletto** [comment]
If I restart Home Assistant everything is normal, but if I do a reload of the integration I get this error.

**Comment by vindaalex** [comment]
I did quite some changes to the code the last few weeks. You could give the new version a try. In this version the default hvac mode is off instead of None. Maybe it solves your error.

Please read the readme for config changes, such as:
- sensor_filter definition changed position
- window open check

**Comment by mycanaletto** [comment]
I will test it, but what would be nice is to integrate it with HACS...

**Comment by vindaalex** [comment]
I've updated hacs part and hope it will be accepted to be available in hacs
